services:
  - type: web
    name: bgm-enhancer-api
    env: debian
    plan: free
    branch: main
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      source venv/bin/activate
      uvicorn main:app --host 0.0.0.0 --port $PORT
